#!/usr/bin/env python3
"""
Aggregate the P8 SPY proxy-label stress-test results into a per-axis,
per-method, per-level summary suitable for the appendix table.

Reads:  results/p8_spy_proxy_stress/spy_p8_<axis>_<level>_<method>_s<seed>.json
Writes: papers/neurips_DB/evidence/p8_summary.json
        papers/neurips_DB/evidence/p8_summary.md  (reviewer-readable)
        papers/neurips_DB/evidence/p8_summary.tex (paste-ready table body)
"""
from __future__ import annotations

import json
from collections import defaultdict
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[3]
import sys as _sys
_sys.path.insert(0, str(ROOT))
from dml_benchmark.io import load_result_json
SRC = ROOT / "results" / "p8_spy_proxy_stress"
OUT_JSON = ROOT / "papers/neurips_DB/evidence/p8_summary.json"
OUT_MD = ROOT / "papers/neurips_DB/evidence/p8_summary.md"
OUT_TEX = ROOT / "papers/neurips_DB/evidence/p8_summary.tex"

METHOD_ORDER = ["vanilla", "dml_fixed", "dml_gradnorm", "dml_relobralo", "dml_warmup"]


def load() -> dict:
    by_axis_level_method = defaultdict(lambda: defaultdict(list))
    for p in SRC.glob("*.json"):
        r = load_result_json(p)
        if r is None:
            continue
        axis = r.get("axis")
        level = r.get("axis_label")
        method = r.get("method")
        if None in (axis, level, method):
            continue
        v = r.get("test_value_mse")
        g = r.get("test_grad_mse")
        if v is None or g is None:
            continue
        by_axis_level_method[(axis, level)][method].append(
            {"value_mse": float(v), "grad_mse": float(g), "seed": r.get("seed")}
        )
    return by_axis_level_method


def summarise(by_axis_level_method) -> dict:
    out = {"axes": {}, "n_total_runs": 0}
    for (axis, level), methods in sorted(by_axis_level_method.items()):
        cell = out["axes"].setdefault(axis, {}).setdefault(level, {})
        for m in METHOD_ORDER:
            runs = methods.get(m, [])
            if not runs:
                continue
            out["n_total_runs"] += len(runs)
            v = np.array([x["value_mse"] for x in runs])
            g = np.array([x["grad_mse"] for x in runs])
            cell[m] = {
                "n_seeds": len(runs),
                "value_mse_mean": float(v.mean()),
                "value_mse_std": float(v.std(ddof=1)) if len(v) > 1 else 0.0,
                "grad_mse_mean": float(g.mean()),
                "grad_mse_std": float(g.std(ddof=1)) if len(g) > 1 else 0.0,
            }
    return out


def render_md(summary) -> str:
    lines = [
        "# P8 SPY proxy-label stress test — summary",
        "",
        f"Total runs aggregated: **{summary['n_total_runs']}**.",
        "",
        "Each cell shows (value MSE mean ± std) / (grad MSE mean ± std) over 5 seeds.",
        "",
    ]
    for axis, levels in summary["axes"].items():
        lines.append(f"## Axis: `{axis}`")
        lines.append("")
        for level, methods in sorted(levels.items()):
            lines.append(f"### Level: `{level}`")
            lines.append("")
            lines.append("| Method | n | value MSE (×1e-5) | grad MSE (×1e-5) |")
            lines.append("|---|---:|---:|---:|")
            for m in METHOD_ORDER:
                if m not in methods:
                    continue
                d = methods[m]
                lines.append(
                    f"| {m} | {d['n_seeds']} | "
                    f"{1e5 * d['value_mse_mean']:.2f} ± {1e5 * d['value_mse_std']:.2f} | "
                    f"{1e5 * d['grad_mse_mean']:.2f} ± {1e5 * d['grad_mse_std']:.2f} |"
                )
            lines.append("")
    return "\n".join(lines)


def baseline_grad_mse(summary, method):
    """Return baseline grad MSE for a method, used to compute degradation factors."""
    base = summary["axes"].get("baseline", {}).get("baseline", {}).get(method)
    return base["grad_mse_mean"] if base else None


def render_tex(summary) -> str:
    """Compact LaTeX table body: per-axis, per-level, gradient MSE degradation factor
    for dml_fixed vs baseline (the headline number for the appendix)."""
    base_dml = baseline_grad_mse(summary, "dml_fixed")
    base_van = baseline_grad_mse(summary, "vanilla")
    lines = [
        "% auto-generated by p8_aggregate.py — do not edit by hand",
        "\\begin{tabular}{lll rr rr}",
        "\\toprule",
        "Axis & Level & \\texttt{dml\\_fixed} & \\texttt{dml\\_fixed} & "
        "\\texttt{vanilla} & \\texttt{vanilla} \\\\",
        " & & grad MSE & $\\times$ baseline & grad MSE & $\\times$ baseline \\\\",
        "\\midrule",
    ]
    for axis, levels in summary["axes"].items():
        if axis == "baseline":
            continue
        for level, methods in sorted(levels.items()):
            dml = methods.get("dml_fixed")
            van = methods.get("vanilla")
            row_axis = axis if level == sorted(levels.keys())[0] else ""
            level_short = level.replace(f"{axis}_", "")
            dml_str = (f"{1e5*dml['grad_mse_mean']:.2f}", f"{dml['grad_mse_mean']/base_dml:.2f}") if (dml and base_dml) else ("--", "--")
            van_str = (f"{1e5*van['grad_mse_mean']:.2f}", f"{van['grad_mse_mean']/base_van:.2f}") if (van and base_van) else ("--", "--")
            lines.append(
                f"{row_axis} & \\texttt{{{level_short}}} & "
                f"{dml_str[0]} & {dml_str[1]} & "
                f"{van_str[0]} & {van_str[1]} \\\\"
            )
    lines += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(lines)


def main():
    raw = load()
    if not raw:
        print(f"no result files found in {SRC}")
        return
    summary = summarise(raw)
    OUT_JSON.write_text(json.dumps(summary, indent=2))
    OUT_MD.write_text(render_md(summary))
    OUT_TEX.write_text(render_tex(summary))
    print(f"wrote {OUT_JSON}")
    print(f"wrote {OUT_MD}")
    print(f"wrote {OUT_TEX}")
    print(f"total runs aggregated: {summary['n_total_runs']}")
    print(f"axes covered: {list(summary['axes'].keys())}")


if __name__ == "__main__":
    main()
